### ISSUE TITLE
hmat assembly test segfaults

### ISSUE THREAD

**Issue by thisch** [bempp/bempp#262]
In the devel branch and probably also in the master branch the ``bempp.api.hmat.test.test_hmatrix_assembly.TestHMatrixAssembly`` test segfaults. In order to compile bempp on a fedora 23 system, I had to manually compile an older version (3.1.2) of cmake (due to #258). 

Here is the gdb output:

```
$ gdb python
GNU gdb (GDB) Fedora 7.10.1-30.fc23
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copy                                                           ing"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python...done.
(gdb) run  -m unittest bempp.api.hmat.test.test_hmatrix_assembly.TestHMatrixAssembly
Starting program: /home/jenkins/miniconda/envs/bempp_development/bin/python -m unittest bempp.api.hmat.test.test_hmatrix_assembly.TestHMatrixAssembly
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.22-9.f                                                           c23.x86_64
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Missing separate debuginfo for /home/jenkins/miniconda/envs/bempp_deve                                                           (gdb) Missing separate debuginfo for /home/jenkins/miniconda/envs/bempp_development/lib/python2.7/site-packages/scipy/sparse/linalg/isolve/../../../../../../libgfortran.so.1
Detaching after fork from child process 14390.
[New Thread 0x7fffd9956700 (LWP 14404)]
[New Thread 0x7fffd9154700 (LWP 14406)]
[New Thread 0x7fffd9555700 (LWP 14405)]

Program received signal SIGSEGV, Segmentation fault.
Bempp::DiscreteBoundaryOperator<std::complex<double> >::apply (this=0x5a1f860, trans=Bempp::NO_TRANSPOSE, 
    x_in=x_in@entry=0x7fffdf3d9760)
    at /home/jenkins/miniconda/envs/bempp_development/bempp/lib/assembly/discrete_boundary_operator.cpp:176
176	          PyArray_DATA(reinterpret_cast<PyArrayObject *>(y_inout))),
Missing separate debuginfos, use: dnf debuginfo-install libgcc-5.3.1-2.fc23.x86_64 libstdc++-5.3.1-2.fc23.x86_64


(gdb) bt
#0  Bempp::DiscreteBoundaryOperator<std::complex<double> >::apply (this=0x5a1f860, trans=Bempp::NO_TRANSPOSE, 
    x_in=x_in@entry=0x7fffdf3d9760)
    at /home/jenkins/miniconda/envs/bempp_development/bempp/lib/assembly/discrete_boundary_operator.cpp:176
#1  0x00007fffdddaeb93 in __pyx_pf_5bempp_4core_8assembly_26discrete_boundary_operator_31ComplexDiscreteBoundaryOperator_8matvec
    (__pyx_v_x=<optimized out>, __pyx_v_self=0x7fffdbf67148)
    at /home/jenkins/miniconda/envs/bempp_development/bempp/build/cython/bempp/core/assembly/cython_discrete_boundary_operator.cc:4346
#2  __pyx_pw_5bempp_4core_8assembly_26discrete_boundary_operator_31ComplexDiscreteBoundaryOperator_9matvec (
    __pyx_v_self=0x7fffdbf67148, __pyx_v_x=<optimized out>)
    at /home/jenkins/miniconda/envs/bempp_development/bempp/build/cython/bempp/core/assembly/cython_discrete_boundary_operator.cc:4092
#3  0x00007fffdddad53d in __Pyx_PyObject_CallMethO (arg=0x7fffdf3d9710, func=0x7fffdf44bb48)
    at /home/jenkins/miniconda/envs/bempp_development/bempp/build/cython/bempp/core/assembly/cython_discrete_boundary_operator.cc:7996
#4  __Pyx_PyObject_CallOneArg (arg=0x7fffdf3d9710, func=0x7fffdf44bb48)
    at /home/jenkins/miniconda/envs/bempp_development/bempp/build/cython/bempp/core/assembly/cython_discrete_boundary_operator.cc:8025
#5  __pyx_pf_5bempp_4core_8assembly_26discrete_boundary_operator_31ComplexDiscreteBoundaryOperator_10matmat (
    __pyx_v_x=0x7fffdf3d9710, __pyx_v_self=<optimized out>)
    at /home/jenkins/miniconda/envs/bempp_development/bempp/build/cython/bempp/core/assembly/cython_discrete_boundary_operator.cc:4496
#6  __pyx_pw_5bempp_4core_8assembly_26discrete_boundary_operator_31ComplexDiscreteBoundaryOperator_11matmat (
    __pyx_v_self=<optimized out>, __pyx_v_x=0x7fffdf3d9710)
    at /home/jenkins/miniconda/envs/bempp_development/bempp/build/cython/bempp/core/assembly/cython_discrete_boundary_operator.cc:4452
#7  0x00007ffff7af20e6 in call_function (oparg=<optimized out>, pp_stack=0x7fffffff9f88) at Python/ceval.c:4338
#8  PyEval_EvalFrameEx (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:2987
#9  0x00007ffff7af1b95 in fast_function (nk=<optimized out>, na=<optimized out>, n=<optimized out>, pp_stack=0x7fffffffa0f8, 
    func=0x7fffe1c4b7d0) at Python/ceval.c:4436
#10 call_function (oparg=<optimized out>, pp_stack=0x7fffffffa0f8) at Python/ceval.c:4371
#11 PyEval_EvalFrameEx (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:2987
#12 0x00007ffff7af2a2e in PyEval_EvalCodeEx (co=0x7fffe755b7b0, globals=<optimized out>, locals=<optimized out>, 
    args=<optimized out>, argcount=2, kws=0x7fffe17b2c98, kwcount=0, defs=0x0, defcount=0, closure=0x0) at Python/ceval.c:3582
#13 0x00007ffff7af1a55 in fast_function (nk=<optimized out>, na=2, n=<optimized out>, pp_stack=0x7fffffffa318, 
    func=0x7fffe756f500) at Python/ceval.c:4446
#14 call_function (oparg=<optimized out>, pp_stack=0x7fffffffa318) at Python/ceval.c:4371
#15 PyEval_EvalFrameEx (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:2987
#16 0x00007ffff7af2a2e in PyEval_EvalCodeEx (co=0x7fffe755b930, globals=<optimized out>, locals=<optimized out>, 
    args=<optimized out>, argcount=2, kws=0x7fffdbf6a8e8, kwcount=0, defs=0x0, defcount=0, closure=0x0) at Python/ceval.c:3582
#17 0x00007ffff7af1a55 in fast_function (nk=<optimized out>, na=2, n=<optimized out>, pp_stack=0x7fffffffa538, 
    func=0x7fffe756f668) at Python/ceval.c:4446
#18 call_function (oparg=<optimized out>, pp_stack=0x7fffffffa538) at Python/ceval.c:4371
#19 PyEval_EvalFrameEx (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:2987
#20 0x00007ffff7af2a2e in PyEval_EvalCodeEx (co=0x7fffe755b8b0, globals=<optimized out>, locals=<optimized out>, 
    args=<optimized out>, argcount=2, kws=0x0, kwcount=0, defs=0x0, defcount=0, closure=0x0) at Python/ceval.c:3582
#21 0x00007ffff7a6e3a1 in function_call (func=0x7fffe756f5f0, arg=0x7fffdf44bbd8, kw=0x0) at Objects/funcobject.c:526
#22 0x00007ffff7a3ed23 in PyObject_Call (func=0x7fffe756f5f0, arg=<optimized out>, kw=<optimized out>)
    at Objects/abstract.c:2546
#23 0x00007ffff7a514bf in instancemethod_call (func=0x7fffe756f5f0, arg=0x7fffdf44bbd8, kw=0x0) at Objects/classobject.c:2602

```

**Comment by tbetcke** [comment]
Hi Thomas,

thanks for your report. It is fixed now. It was actually a bug in the unit test. We changed the sphere shape function a few days ago to allow varying radii. Unfortunately, the unit test was calling this function incorrectly from the start and now after the modification the unit test tried to create dense matrices with almost 50k elements, which will crash most machines.

Regarding your cmake issue. This is a problem in Dune. I have patches for it. But we are making some major changes to our Dune interface and upgrade the Dune version to 2.4. This should be ready in time for the next Ubuntu LTS release in April, which is our main Linux target platform.

Best wishes

Timo

**Comment by thisch** [comment]
Hey Timo, 

thx for the quick fix. Good to know that it was just a bug in the unit test. Now all unit tests pass.

Best regards
Thomas
