### ISSUE TITLE
problem using adjoint operator

### ISSUE THREAD

**Issue by arieder** [bempp/bempp#263]
Hi,
I'm trying to use the adjoint of some boundary operators, but a I keep getting an error. The following simple test case fails:
```
import bempp.api 
grid=bempp.api.shapes.regular_sphere(1)
const_space = bempp.api.function_space(grid, "DP", 0)  
lin_space = bempp.api.function_space(grid, "P", 1)

hyp = bempp.api.operators.boundary.modified_helmholtz.hypersingular(lin_space,const_space,lin_space,1.0);

C=hyp.adjoint(const_space).weak_form(),

```
It fails with the following error message:

```
Traceback (most recent call last):
  File "test_adjoin.py", line 11, in <module>
    C=hyp.adjoint(const_space).weak_form()
  File "/home/ar/devel/install/bempp3/lib/python3.4/site-packages/bempp/api/assembly/boundary_operator.py", line 81, in weak_form
    self._weak_form = self._weak_form_impl()
  File "/home/ar/devel/install/bempp3/lib/python3.4/site-packages/bempp/api/assembly/boundary_operator.py", line 497, in _weak_form_impl
    return self._op.weak_form().adjoint()
  File "/home/ar/.local/lib/python3.4/site-packages/scipy/sparse/linalg/interface.py", line 429, in adjoint
    return self._adjoint()
  File "/home/ar/devel/install/bempp3/lib/python3.4/site-packages/bempp/api/assembly/discrete_boundary_operator.py", line 32, in _adjoint
    return GeneralNonlocalDiscreteBoundaryOperator(self._impl.adjoint())
  File "bempp/core/assembly/discrete_boundary_operator.pyx", line 226, in bempp.core.assembly.discrete_boundary_operator.ComplexDiscreteBoundaryOperator.adjoint (/home/ar/devel/src/bempp3/build/cython/bempp/core/assembly/cython_discrete_boundary_operator.cc:4909)
NameError: name 'enums' is not defined

```

Interestingly enough it works if I replace adjoint with the transpose. Am I doing something wrong or is there some bug in Bem++? (I tested both master and the development branch)

Cheers,
Alex

**Comment by tbetcke** [comment]
Hi,

there was a bug in the adjoint method. I have fixed it and updated the development branch. Thanks for spotting this.

Timo
