### ISSUE TITLE
reduced accuracy in bempp3 script compared to bempp2 

### ISSUE THREAD

**Issue by thisch** [bempp/bempp#266]
Hi,

In this [gist](https://gist.github.com/thisch/104ee0bac5809d5f4b04) I evaluate one of the radiating solutions of maxwells equations, which is  also used in the bempp preprint, and compare the field at a certain radius with the analytical field using a L2-Norm on a sphere. With bempp2 this test worked well and resulted in a good accurracy (rel error 1.123444E-06),  but with bempp3 I get a much higher error (rel error 5.267149E-03). Do you have an idea what parameter needs to be set in bempp to achieve the same accuracy as with bempp2?

here is the bempp3 output:
```
DEBUG:root:DIR [-0.75193882  0.23682471 -0.6000257 ] val: [(-0.1039835090841613+0.086305491538619619j), (-0.33015658066050768+0.27402735519872223j), 0.0]
INFO:BEMPP:IDENTITY. START ASSEMBLY. Dim: (3084,3084). Assembly Type: sparse
INFO:BEMPP:IDENTITY. FINISHED ASSEMBLY. Time: 4.83E-03 sec.
DEBUG:root:   assembling of dirichlet trace took 148.791075 ms
DEBUG:root:NEU [-0.75193882  0.23682471 -0.6000257 ] val: [(0.18008680265350077-0.68777427162133797j), (-0.056718717046907605+0.21661595258199404j), (0.63008031975112533+0.21854428981636023j)]
INFO:BEMPP:IDENTITY. START ASSEMBLY. Dim: (3084,3084). Assembly Type: sparse
INFO:BEMPP:IDENTITY. FINISHED ASSEMBLY. Time: 4.80E-03 sec.
DEBUG:root:   assembling of neumann trace took 186.649799 ms
INFO:root:### rfac = 1.4
DEBUG:root:::bem_eval_at_points called (point shape (3, 1024), #chunks 3, cs: 400)
INFO:BEMPP:POTENTIAL OPERATOR ASSEMBLY START. Number of points: 400. Space dimension: 3084. Assembly type: hmat 
INFO:BEMPP:FINISHED POTENTIAL OPERATOR ASSEMBLY. Time: 1.03E+00 sec.
DEBUG:root:setup of MW EFPO took 1027.947903 ms
INFO:BEMPP:POTENTIAL OPERATOR ASSEMBLY START. Number of points: 400. Space dimension: 3084. Assembly type: hmat 
INFO:BEMPP:FINISHED POTENTIAL OPERATOR ASSEMBLY. Time: 1.24E+00 sec.
DEBUG:root:setup of MW MFPO took 1239.413023 ms
DEBUG:root:[1/3] setting up of Maxw. OPS took 2267.443 ms (pshape (3, 400))
DEBUG:root:::_eval_potops_at_points (sl part) took 1.772881 ms
DEBUG:root:::_eval_potops_at_points (dl part) took 1.577139 ms
INFO:root:::_eval_potops_at_points (sl+dl part) took 3.564119 ms
DEBUG:root:::_eval_potops_at_points (sl curl part) took 1.443148 ms
DEBUG:root:::_eval_potops_at_points (dl curl part) took 1.553059 ms
INFO:root:::_eval_potops_at_points (sl+dl curl part) took 3.229141 ms
INFO:BEMPP:POTENTIAL OPERATOR ASSEMBLY START. Number of points: 400. Space dimension: 3084. Assembly type: hmat 
INFO:BEMPP:FINISHED POTENTIAL OPERATOR ASSEMBLY. Time: 1.20E+00 sec.
DEBUG:root:setup of MW EFPO took 1199.844122 ms
INFO:BEMPP:POTENTIAL OPERATOR ASSEMBLY START. Number of points: 400. Space dimension: 3084. Assembly type: hmat 
INFO:BEMPP:FINISHED POTENTIAL OPERATOR ASSEMBLY. Time: 1.43E+00 sec.
DEBUG:root:setup of MW MFPO took 1432.374001 ms
DEBUG:root:[2/3] setting up of Maxw. OPS took 2633.071 ms (pshape (3, 400))
DEBUG:root:::_eval_potops_at_points (sl part) took 1.725197 ms
DEBUG:root:::_eval_potops_at_points (dl part) took 1.756907 ms
INFO:root:::_eval_potops_at_points (sl+dl part) took 3.680944 ms
DEBUG:root:::_eval_potops_at_points (sl curl part) took 1.654863 ms
DEBUG:root:::_eval_potops_at_points (dl curl part) took 1.425028 ms
INFO:root:::_eval_potops_at_points (sl+dl curl part) took 3.282070 ms
INFO:BEMPP:POTENTIAL OPERATOR ASSEMBLY START. Number of points: 224. Space dimension: 3084. Assembly type: hmat 
INFO:BEMPP:FINISHED POTENTIAL OPERATOR ASSEMBLY. Time: 3.83E-01 sec.
DEBUG:root:setup of MW EFPO took 382.725000 ms
INFO:BEMPP:POTENTIAL OPERATOR ASSEMBLY START. Number of points: 224. Space dimension: 3084. Assembly type: hmat 
INFO:BEMPP:FINISHED POTENTIAL OPERATOR ASSEMBLY. Time: 3.67E-01 sec.
DEBUG:root:setup of MW MFPO took 367.268085 ms
DEBUG:root:[3/3] setting up of Maxw. OPS took 751.775 ms (pshape (3, 224))
DEBUG:root:::_eval_potops_at_points (sl part) took 0.568151 ms
DEBUG:root:::_eval_potops_at_points (dl part) took 1.224041 ms
INFO:root:::_eval_potops_at_points (sl+dl part) took 1.888037 ms
DEBUG:root:::_eval_potops_at_points (sl curl part) took 0.586033 ms
DEBUG:root:::_eval_potops_at_points (dl curl part) took 0.597954 ms
INFO:root:::_eval_potops_at_points (sl+dl curl part) took 1.255989 ms
DEBUG:root:bempp field r: [-8.027626E-02, 8.002387E-02, 1.080405E-04]
DEBUG:root:exact field r: [-8.027733E-02, 8.027733E-02, 0.000000E+00]
INFO:root:	( relerr: 5.267149E-03 )
Traceback (most recent call last):
  File "standalone_bempp_mw_test.py", line 354, in <module>
    main()
  File "standalone_bempp_mw_test.py", line 352, in main
    assert relerror < 1.5e-6
AssertionError
```

and here the same when run with bempp2
```
DEBUG:root:DIR [-0.7259325   0.22580583 -0.63505371] val: [(-0.099157542333044552+0.082336263829533893j), (-0.318776903202308+0.26469896880532268j), 0.0]
DEBUG:root:   assembling of dirichlet trace took 275.151968 ms
DEBUG:root:NEU [-0.7259325   0.22580583 -0.63505371] val: [(0.18402294035395372-0.70313903529396571j), (-0.057241482413228947+0.21871577883398147j), (0.64754422715200233+0.15226374825096439j)]
DEBUG:root:   assembling of neumann trace took 377.207994 ms
INFO:root:### rfac = 1.4
DEBUG:root:::bem_eval_at_points called (point shape (3, 1024), aca=True, #chunks 3, cs: 400)
DEBUG:root:[1/3] setting up of Maxw. OPS took 0.029 ms (pshape (3, 400))
About to start the ACA assembly loop
Approximating ... [####################] 100%
ACA loop took 0.412772 s

Needed storage: 19.9081 MB.
Without approximation: 56.4697 MB.
Compressed to 35.2544%.
Maximum rank: 58.
Accessed 56.1557% matrix entries.

Assembling the weak form of operator 'Op1'...
Collecting data for assembler construction...
Data collection finished.
Assembly of the weak form of operator 'Op1' took 0.00538437 s
Calculating the (pseudo)inverse of operator 'Op1'...
Calculation of the (pseudo)inverse of operator 'Op1' took 0.0033133 s
DEBUG:root:::_eval_potops_at_points (sl part) took 426.030874 ms
About to start the ACA assembly loop
Approximating ... [####################] 100%
ACA loop took 0.331803 s

Needed storage: 18.7807 MB.
Without approximation: 56.4697 MB.
Compressed to 33.2581%.
Maximum rank: 55.
Accessed 53.0997% matrix entries.

Assembling the weak form of operator 'Op2'...
Collecting data for assembler construction...
Data collection finished.
Assembly of the weak form of operator 'Op2' took 0.00555557 s
Calculating the (pseudo)inverse of operator 'Op2'...
Calculation of the (pseudo)inverse of operator 'Op2' took 0.00314504 s
DEBUG:root:::_eval_potops_at_points (dl part) took 345.265150 ms
INFO:root:::_eval_potops_at_points (sl+dl part) took 771.557093 ms
About to start the ACA assembly loop
Approximating ... [####################] 100%
ACA loop took 0.409079 s

Needed storage: 19.9081 MB.
Without approximation: 56.4697 MB.
Compressed to 35.2544%.
Maximum rank: 58.
Accessed 56.1557% matrix entries.

DEBUG:root:::_eval_potops_at_points (sl curl part) took 413.269997 ms
About to start the ACA assembly loop
Approximating ... [####################] 100%
ACA loop took 0.332204 s

Needed storage: 18.7807 MB.
Without approximation: 56.4697 MB.
Compressed to 33.2581%.
Maximum rank: 55.
Accessed 53.0997% matrix entries.

Assembling the weak form of operator 'Op3'...
Collecting data for assembler construction...
Data collection finished.
Assembly of the weak form of operator 'Op3' took 0.00520749 s
Calculating the (pseudo)inverse of operator 'Op3'...
Calculation of the (pseudo)inverse of operator 'Op3' took 0.00303516 s
DEBUG:root:::_eval_potops_at_points (dl curl part) took 345.010996 ms
INFO:root:::_eval_potops_at_points (sl+dl curl part) took 758.538008 ms
DEBUG:root:[2/3] setting up of Maxw. OPS took 0.033 ms (pshape (3, 400))
About to start the ACA assembly loop
Approximating ... [####################] 100%
ACA loop took 0.541518 s

Needed storage: 25.9921 MB.
Without approximation: 56.4697 MB.
Compressed to 46.0283%.
Maximum rank: 38.
Accessed 75.0194% matrix entries.

DEBUG:root:::_eval_potops_at_points (sl part) took 547.111988 ms
About to start the ACA assembly loop
Approximating ... [####################] 100%
ACA loop took 0.442427 s

Needed storage: 24.7655 MB.
Without approximation: 56.4697 MB.
Compressed to 43.8562%.
Maximum rank: 36.
Accessed 72.6138% matrix entries.

DEBUG:root:::_eval_potops_at_points (dl part) took 447.391033 ms
INFO:root:::_eval_potops_at_points (sl+dl part) took 994.724989 ms
About to start the ACA assembly loop
Approximating ... [####################] 100%
ACA loop took 0.542303 s

Needed storage: 25.9921 MB.
Without approximation: 56.4697 MB.
Compressed to 46.0283%.
Maximum rank: 38.
Accessed 75.0194% matrix entries.

DEBUG:root:::_eval_potops_at_points (sl curl part) took 547.443151 ms
About to start the ACA assembly loop
Approximating ... [####################] 100%
ACA loop took 0.44269 s

Needed storage: 24.7655 MB.
Without approximation: 56.4697 MB.
Compressed to 43.8562%.
Maximum rank: 36.
Accessed 72.6138% matrix entries.

Assembling the weak form of operator 'Op4'...
Collecting data for assembler construction...
Data collection finished.
Assembly of the weak form of operator 'Op4' took 0.00513801 s
Calculating the (pseudo)inverse of operator 'Op4'...
Calculation of the (pseudo)inverse of operator 'Op4' took 0.00305781 s
DEBUG:root:::_eval_potops_at_points (dl curl part) took 456.088066 ms
INFO:root:::_eval_potops_at_points (sl+dl curl part) took 1003.736973 ms
DEBUG:root:[3/3] setting up of Maxw. OPS took 0.028 ms (pshape (3, 224))
About to start the ACA assembly loop
Approximating ... [####################] 100%
ACA loop took 0.312239 s

Needed storage: 11.1851 MB.
Without approximation: 31.623 MB.
Compressed to 35.3702%.
Maximum rank: 80.
Accessed 53.2769% matrix entries.

DEBUG:root:::_eval_potops_at_points (sl part) took 315.622091 ms
About to start the ACA assembly loop
Approximating ... [####################] 100%
ACA loop took 0.228356 s

Needed storage: 10.4444 MB.
Without approximation: 31.623 MB.
Compressed to 33.0279%.
Maximum rank: 73.
Accessed 51.1433% matrix entries.

DEBUG:root:::_eval_potops_at_points (dl part) took 231.665850 ms
INFO:root:::_eval_potops_at_points (sl+dl part) took 547.502995 ms
About to start the ACA assembly loop
Approximating ... [####################] 100%
ACA loop took 0.294738 s

Needed storage: 11.1851 MB.
Without approximation: 31.623 MB.
Compressed to 35.3702%.
Maximum rank: 80.
Accessed 53.2769% matrix entries.

DEBUG:root:::_eval_potops_at_points (sl curl part) took 298.062086 ms
About to start the ACA assembly loop
Approximating ... [####################] 100%
ACA loop took 0.225388 s

Needed storage: 10.4444 MB.
Without approximation: 31.623 MB.
Compressed to 33.0279%.
Maximum rank: 73.
Accessed 51.1433% matrix entries.

Assembling the weak form of operator 'Op5'...
Collecting data for assembler construction...
Data collection finished.
Assembly of the weak form of operator 'Op5' took 0.00517923 s
Calculating the (pseudo)inverse of operator 'Op5'...
Calculation of the (pseudo)inverse of operator 'Op5' took 0.00307198 s
DEBUG:root:::_eval_potops_at_points (dl curl part) took 237.259150 ms
INFO:root:::_eval_potops_at_points (sl+dl curl part) took 535.548925 ms
DEBUG:root:field r:       [-8.022035E-02, 8.018219E-02, -4.841147E-05]
DEBUG:root:exact field r: [-8.027733E-02, 8.027733E-02, 0.000000E+00]
INFO:root:	( relerr: 1.123444E-06 )
```

Best regards,
Thomas

**Comment by tbetcke** [comment]
Hi Thomas, 

Have you tried increasing the Quadrature orders?  We  have completely reworked the definitions of the default  orders for Bem++3. The documentation has more information about it.

**Comment by thisch** [comment]
Yes, I have tried that, but it doesn't seem to have an influence on the obtained accuracy.

**Comment by thisch** [comment]
The reason why I introduced the pointlist chunking code is that I ran out of mem for some of my studied systems if the number of evaluation points is large (~1000).  Removing the chunking code  (``chunks = [points.T]``) from the posted minimal example reduces the rel. error by a factor 1e3, but it still does not reach the rel.error obtained with bempp2.9, which I don't understand.  I doubt that there is a bug in my chunking algorithm since ``chunks = [points.T[:400, :], points.T[400:800, :], points.T[800:, :]]`` leads to the same bad rel. error (6e-3). Surprisingly `` chunks = [points.T[:500, :], points.T[500:, :]]`` leads to a better relerror (3e-6).

**Comment by tbetcke** [comment]
Now I understand.  Your 2.9 version still uses dense evaluation of
potentials by default. In version 3.0 by default we use H-matrix evaluation
of potentials with accuracy 1E-3, which you can modify.

To switch on dense potentials use
bempp.api.global_parameters.assembly.potential_operator_assembly_type='dense'

Best wishes

Timo

**Comment by tbetcke** [comment]
By the way, I would stay with H-matrix assembly for the potentials and set
a smaller tolerance for them. This should solve your memory problems.
Hierarchical assembly is hugely more efficient for potentials.

**Comment by thisch** [comment]
Setting the assembly type to dense fixes the accuracy problem with bempp3. Thx!
I guess that Hierarchical assembly is more efficient only in terms of memory and not in terms of speed.
I'll try to evaluate which parameters work best for my problems. 

Best regards,
Thomas
